@groovy.transform.Field
def version

@groovy.transform.Field
def imageName

@groovy.transform.Field
def registry
pipeline {
    agent {
	label 'api-test'
	}
    stages {
		stage('Prepare') {
            steps {
                script{
					version = sh(
					script: "cat package.json | grep version | head -1 | awk -F: '{ print \$2 }' | sed 's/[\",]//g'",
					returnStdout: true
					).trim()
					
					imageName = sh(
					script: "cat package.json | grep name | head -1 | awk -F: '{ print \$2 }' | sed 's/[\",]//g'",
					returnStdout: true
					).trim()                 
                    
                }
            }
        }	
        stage('Build UI') {
            steps {
                script{
                            
					sh 'npm install --prefer-offline --no-audit --progress=false'
					sh 'npm run build --prefer-offline --no-audit --progress=false'
                    
                    
                }
            }
        }	
	}	
}
